### ISSUE TITLE
Not working with SvelteKit

### ISSUE THREAD

**Issue by Yash-Punia** [wdtamagi/svelte-avatar#19]
While creating a project through SvelteKit, I faced strange issues, screenshot given below
![image](https://user-images.githubusercontent.com/21677583/136096018-e4922976-ba1d-4cd5-96ae-16d730d93492.png)

I believe that Vite is unable to process the Avatar.svelte for some reason, as I can see in the console that there is some error when evaluating SSR module.

Is svelte-avatar compatible with SvelteKit for now?

**Comment by wdtamagi** [comment]
Hi @Yash-Punia 

Thank you for the report, I don't think that svelte-avatar is compatible with SvelteKit now, but I can check it this week or earlier next week and try do make it compatible.

**Comment by wdtamagi** [comment]
@Yash-Punia 

I figure out that it is happening because of a package that svelte-avatar have dependency, I will work to remove this package and it will be solved in the svelte-avatar side.
 
For now a workaround that you can do is add the `initials` to the include at vite optimizeDeps inside your svelte.config.js like this:

```diff
# svelte.config.js
export default {
  kit: {
    target: "#svelte",
+   vite: {
+     optimizeDeps: {
+       include: ["initials"],
+     },
+   },
  },
};

**Comment by wdtamagi** [comment]
Leaving this issue open for remove the `initials` package from the svelte-avatar, it will fix the sveltekit support and reduce our bundle size as well.

**Comment by wdtamagi** [comment]
Package initials was removed into the #27
